name: Environment Variables

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v6.0.2

      - name: Configure environment variable
        run: echo 'MY_VARIABLE=hello, world, github actions' >> $GITHUB_ENV
      
      - name: execute the JS file
        run: node main.js

    
