name: Passing values between steps

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Write a variable
      id: generate-value
      run: echo "MY_VALUE=Felipe" >> "$GITHUB_OUTPUT"

    - name: Getting a variable
      run: echo "${{ steps.generate-value.outputs.MY_VALUE }}"
